In [1]:
import numpy as np


In [3]:
t1 = np.arange(12)
t1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
t1.shape

In [5]:
t2 =np.array([[1,2,3],[4,5,6]])
t2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
t2.shape

(2, 3)

In [7]:
t4 = np.arange(12)
t4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
t4.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
t5 = np.arange(24).reshape(2,3,4)
t5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
t5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [12]:
t5.reshape((4,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
t5 = t5.reshape((4,6))

In [15]:
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
t5.reshape((24,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
t5 = np.arange(24).reshape(4,6)

In [18]:
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
t6 = np.arange(100,124).reshape(4,6)
t6

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [1]:
t6+t5

NameError: name 't6' is not defined

In [4]:
t2 = np.arange(24).reshape(4,6)

NameError: name 'np' is not defined

In [5]:
import numpy as np

In [6]:
t2 = np.arange(24).reshape(4,6)

In [7]:
t2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
t2<10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [9]:
t2[t2<10]=3

In [10]:
t2

array([[ 3,  3,  3,  3,  3,  3],
       [ 3,  3,  3,  3, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
t2[t2>20]

array([21, 22, 23])

In [12]:
t2[t2>20]=20

In [13]:
t2

array([[ 3,  3,  3,  3,  3,  3],
       [ 3,  3,  3,  3, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 20, 20, 20]])

In [14]:
np.where(t2<=3,100,300)

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 300, 300],
       [300, 300, 300, 300, 300, 300],
       [300, 300, 300, 300, 300, 300]])

In [15]:
t2 = np.arange(24).reshape(4,6)

In [16]:
t2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [17]:
t2.clip(10,18)

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 18, 18, 18, 18, 18]])

In [18]:
t2[3,3] = np.nan

ValueError: cannot convert float NaN to integer

In [19]:
t2 = t2.astype(float)

In [20]:
t2[3,3] = np.nan

In [21]:
t2

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., nan, 22., 23.]])

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.random.randint(10,20,(4,5))

array([[13, 14, 15, 17, 19],
       [11, 17, 16, 11, 17],
       [19, 11, 14, 14, 11],
       [19, 11, 13, 19, 13]])

In [25]:
np.random.randint(10,20,(4,5))

array([[11, 15, 15, 13, 14],
       [12, 11, 12, 14, 13],
       [12, 11, 12, 10, 19],
       [11, 18, 13, 18, 13]])

In [26]:
np.random.randint(10,20,(4,5))

array([[18, 18, 15, 16, 13],
       [15, 10, 18, 10, 12],
       [19, 16, 12, 10, 16],
       [18, 15, 10, 10, 15]])

In [27]:
np.nan == np.nan

False

In [28]:
np.inf == np.inf

True

In [29]:
t3 = np.arange(12).reshape(3,4)

In [30]:
t3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
np.sum(t3)

66

In [32]:
np.sum(t3,axis=0)

array([12, 15, 18, 21])

In [33]:
np.sum(t3,axis=1)

array([ 6, 22, 38])